# Generated by Django 4.2.5 on 2023-09-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_message_alter_order_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_name',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
