# Generated by Django 4.2.5 on 2023-09-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_address_customer_city_customer_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='state',
        ),
    ]
